package:
  name: struct_llm
  version: 1.0

source:
  path: src/struct_llm

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools


about:
  home: https://github.com/lamalab-org/structllm
  license: 

