finetune:
  exp_name: "train_matbench_perovskites_6"
  path:
    pretrained_checkpoint: "/home/so87pot/n0w0f/structllm/src/structllm/models/pretrain/checkpoints/pretrain_130K/checkpoint-5000"
    finetune_traindata: "/home/so87pot/n0w0f/structllm/data/mb_1/train_matbench_perovskites_4.csv"
    finetune_testdata:
    root_path: "/home/so87pot/n0w0f/structllm/src/structllm/models/finetune"
    output_dir: "${model.finetune.path.root_path}/checkpoints/${model.finetune.exp_name}"
    logging_dir: "${model.finetune.path.root_path}/logs/${model.finetune.exp_name}"
    finetuned_modelname: "${model.finetune.path.root_path}/checkpoints/finetuned_${model.finetune.exp_name}"

  context_length: 128
  training_arguments:
    output_dir: "${model.finetune.path.output_dir}"
    overwrite_output_dir: True
    num_train_epochs: 100
    per_device_train_batch_size: 1024
    save_steps: 500
    logging_steps: 100  
    report_to: "wandb"
    save_total_limit: 5
    learning_rate: 2e-4
    load_best_model_at_end: False
  

pretrain:
  exp_name: "refractor"
  model_name_or_path: "bert-base-uncased"

  model_config:
    hidden_size: 512
    num_hidden_layers: 4
    num_attention_heads: 8
    is_decoder: False
    add_cross_attention: False

  path:
    pretrained_checkpoint: 
    traindata: "/home/so87pot/n0w0f/structllm/data/27k/val.csv"
    evaldata: "/home/so87pot/n0w0f/structllm/data/27k/val.csv"
    root_path: "/home/so87pot/n0w0f/structllm/src/structllm/models/pretrain"
    output_dir: "${model.pretrain.path.root_path}/checkpoints/${model.pretrain.exp_name}"
    logging_dir: "${model.pretrain.path.root_path}/logs/${model.pretrain.exp_name}"
    finetuned_modelname: "${model.pretrain.path.root_path}/output/finetuned_${model.pretrain.exp_name}"

  context_length: 128
  training_arguments:
    output_dir: "${model.pretrain.path.output_dir}"   # Directory where model checkpoints and logs will be saved
    logging_dir: "${model.pretrain.path.logging_dir}"
    overwrite_output_dir: True     
    label_names: ["labels"]
    save_total_limit: 5      # Maximum number of checkpoints to save
    per_device_train_batch_size: 64
    num_train_epochs: 5       # Number of training epochs
    learning_rate: 2e-5
    save_steps: 1000
    report_to: "wandb"
    evaluation_strategy:  'steps'          # check evaluation metrics at each epoch
    logging_steps: 100                    # we will log every 100 steps
    eval_steps: 500                     # we will perform evaluation every 500 steps
    load_best_model_at_end: True

  mlm:
    is_mlm: True 
    mlm_probability: 0.15
