pretrain:
  exp_name: early_stop_implementation
  model_name_or_path: "bert-base-uncased"

  model_config:
    hidden_size: 512
    num_hidden_layers: 4
    num_attention_heads: 8
    is_decoder: False
    add_cross_attention: False

  path:
    pretrained_checkpoint: 
    traindata: "/home/so87pot/n0w0f/structllm/data/27k/train.csv"
    evaldata: "/home/so87pot/n0w0f/structllm/data/27k/val.csv"
    root_path: "/work/so87pot/structllm/model_outs/checkpoints"
    output_dir: "${model.pretrain.path.root_path}/checkpoints/${model.pretrain.exp_name}"
    logging_dir: "${model.pretrain.path.root_path}/logs/${model.pretrain.exp_name}"
    finetuned_modelname: "${model.pretrain.path.root_path}/output/finetuned_${model.pretrain.exp_name}"

  context_length: 128


  callbacks:
    early_stopping: True
    custom_logger: True
    early_stopping_patience: 3
    early_stopping_threshold: 0.001


  training_arguments:
    output_dir: "${model.pretrain.path.output_dir}"   # Directory where model checkpoints and logs will be saved
    logging_dir: "${model.pretrain.path.logging_dir}"
    overwrite_output_dir: True     
    label_names: ["labels"]
    save_total_limit: 5      # Maximum number of checkpoints to save
    per_device_train_batch_size: 256 # Batch size per device during training
    num_train_epochs: 50       # Number of training epochs
    learning_rate: 2e-4
    save_steps: 1000
    report_to: "wandb"
    evaluation_strategy:  'steps'          # check evaluation metrics at each epoch
    logging_steps: 100                    # we will log every 100 steps
    eval_steps: 500                     # we will perform evaluation every 500 steps
    load_best_model_at_end: True
    seed: 42 

  mlm:
    is_mlm: True 
    mlm_probability: 0.15


finetune:
  model_name: early_stop_implementation
  exp_name: [
    "train_matbench_dielectric_0",
    ]
  path:
    pretrained_checkpoint: "/work/so87pot/structllm/model_outs/checkpoints/checkpoints/512cont_atomtok_100_pt/checkpoint-21000"
    finetune_traindata: [
      "/work/so87pot/structllm/finetune_data/csv/train_matbench_dielectric_0.csv",
  
          ]

    finetune_testdata:
    root_path: "/work/so87pot/structllm/model_outs/finetune/${model.finetune.model_name}"
    output_dir: "${model.finetune.path.root_path}/checkpoints/${model.finetune.exp_name}"
    logging_dir: "${model.finetune.path.root_path}/logs/${model.finetune.exp_name}"
    finetuned_modelname: "${model.finetune.path.root_path}/checkpoints/finetuned_${model.finetune.exp_name}"

  context_length: 64
  callbacks:
    early_stopping: True
    custom_logger: True
    early_stopping_patience: 3
    early_stopping_threshold: 0.001

  training_arguments:
    output_dir: "${model.finetune.path.output_dir}"
    overwrite_output_dir: True
    num_train_epochs: 50
    per_device_train_batch_size: 1028
    save_strategy: "epoch"
    evaluation_strategy: "epoch"   
    save_steps: 2  # Number of epochs before saving
    report_to: "wandb"
    save_total_limit: 20
    learning_rate: 2e-4
    logging_steps: 6  
    seed: 42
    eval_steps: 2  # Adjusted evaluation frequency, e.g., evaluate after 10 epochs
    load_best_model_at_end: True
           # check evaluation metrics at each epoch






inference:
  exp_name: [
    "test_matbench_log_kvrh_0",
    "test_matbench_log_kvrh_1",
    "test_matbench_log_kvrh_2",
    "test_matbench_log_kvrh_3",
    "test_matbench_log_kvrh_4",
    ]
  path:
    pretrained_checkpoint: [
    "/work/so87pot/structllm/results/finetune/08_02_100k_bpe_512_wes/checkpoints/finetuned_train_matbench_log_kvrh_0",
    "/work/so87pot/structllm/results/finetune/08_02_100k_bpe_512_wes/checkpoints/finetuned_train_matbench_log_kvrh_1",
    "/work/so87pot/structllm/results/finetune/08_02_100k_bpe_512_wes/checkpoints/finetuned_train_matbench_log_kvrh_2",
    "/work/so87pot/structllm/results/finetune/08_02_100k_bpe_512_wes/checkpoints/finetuned_train_matbench_log_kvrh_3",
    "/work/so87pot/structllm/results/finetune/08_02_100k_bpe_512_wes/checkpoints/finetuned_train_matbench_log_kvrh_4",
   ] 

    test_data: [
    "/home/so87pot/n0w0f/structllm/data/mb_1/csv/test_matbench_log_kvrh_0.csv",
    "/home/so87pot/n0w0f/structllm/data/mb_1/csv/test_matbench_log_kvrh_1.csv",
    "/home/so87pot/n0w0f/structllm/data/mb_1/csv/test_matbench_log_kvrh_2.csv",
    "/home/so87pot/n0w0f/structllm/data/mb_1/csv/test_matbench_log_kvrh_3.csv",
    "/home/so87pot/n0w0f/structllm/data/mb_1/csv/test_matbench_log_kvrh_4.csv",
  ]
    root_path: "/home/so87pot/n0w0f/structllm/src/structllm/models/predictions"
    output_dir: "${model.inference.path.root_path}/checkpoints/${model.inference.exp_name}"
    logging_dir: "${model.inference.path.root_path}/logs/${model.inference.exp_name}"
    predictions: "${model.inference.path.root_path}/checkpoints/inference${model.inference.exp_name}"

  context_length: 512
 