defaults:
  - model: bert
  - tokenizer: bpe
  - matbench: matbench
  - logging: wandb

runs:
  # - name: matbench_predict
  #   tasks: [matbench_predict]

  - name: pretrain_run
    tasks: [pretrain]

  # - name: finetune_run
  #   tasks: [finetune]

  # - name: predict
  #   tasks: [predict]
