hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: pretrain_template
  # - tokenizer: none
  # - matbench: matbench
  # - logging: wandb

runs:

  # - name: benchmark_run
  #   tasks: [benchmark]
    
  # - name: matbench_predict
  #   tasks: [matbench_predict]

  - name: pretrain_run
    tasks: [pretrain]

  # - name: finetune_run
  #   tasks: [finetune]

  # - name: predict
  #   tasks: [predict]

