# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# Slurm specific configurations
partition: gpu
gres: gpu:1
mem_gb: 280
cpus_per_task: 1
signal_delay_s: 120

# Environment modules to load
module_load:
  - nvidia/cuda/11.7

# Activate conda environment
source_activate: /home/so87pot/miniconda3/bin/activate
conda_env: slice_llm

# Set environment variable
env_vars:
  CUDA_LAUNCH_BLOCKING: "1"